name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
        - uses: nguyensonhai/nguyensonhai@master
                with:
                  WAKATIME_API_KEY: ${{ 95354f49-76c0-40b1-94f6-8ff077130d76 }}
                  GH_TOKEN: ${{ 6efcb053996ed0e71a7932feca7ea70ab6d23e62 }}
                  SHOW_COMMIT : "True"
